[global.limits]
forms = 1048576

[development]
address = "localhost"
port = 8000
keep_alive = 5
log = "normal"
url = "http://localhost:8000"

[staging]
address = "0.0.0.0"
port = 8000
keep_alive = 5
log = "normal"
url = "http://localhost:8000"

[production]
address = "0.0.0.0"
port = 8000
keep_alive = 5
log = "critical"
url = "https://cwfitz.com"
